### ISSUE TITLE
Support for IOS 10?

### ISSUE THREAD

**Issue by hslewis** [nfarina/homebridge#662] opened 2016-06-14 03:01 UTC
Hi, Does the current version of home bridge support IOS 10?
I tried to run in on Raspberry Pi 2 with homebridge-platform-wemo.  This is the first time I've run it on that platform. I was able to add the accessory via the Home App on IOS 10 but the wemo devices did not show up. 
(Output below)

(Just FYI: I have a schlage sense which also was not supported (warned of out of date SW))
pi@raspberrypi:~/.homebridge $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
[6/14/2016, 3:25:52 AM] Loaded plugin: homebridge-platform-wemo
[6/14/2016, 3:25:52 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[6/14/2016, 3:25:52 AM] ---
[6/14/2016, 3:25:54 AM] Loaded plugin: homebridge-wemo
[6/14/2016, 3:25:54 AM] Registering accessory 'homebridge-wemo.WeMo'
[6/14/2016, 3:25:54 AM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

[6/14/2016, 3:25:54 AM] Homebridge is running on port 51826.

**Comment by PeterRayBlack1982** [comment] 2016-06-14 03:44
Appears to have broken it for me.  Also the HomeKit Catalog app from apple that I used to configure my HomeKit devices is no longer working

**Comment by sirago** [comment] 2016-06-14 03:56
I had never tried it previously, but I'm getting "Couldn't add accessory"

**Comment by PeterRayBlack1982** [comment] 2016-06-14 03:59
It used to work like a charm.  Guess we will have to wait for a workaround

**Comment by AppleTechy** [comment] 2016-06-14 04:32
What plugins are you running? And have you if you haven't already clear the
persist folder and re pair. Along with the accessories folder

**Comment by sirago** [comment] 2016-06-14 05:28
Mine is a fresh install of homebridge. I get to the point of getting the code on the screen to put into Homekit, enter that into my iPhone, but it doesn't connect.

**Comment by digiltd** [comment] 2016-06-14 11:12
Well it has been less than 24 hours, so you might have to be a little patient :)

(and don't install a beta on something that you rely on)

**Comment by simonrb2000** [comment] 2016-06-14 11:21
I'm sure it will be a simple fix unlike how Apple Stopped Siri Proxy back in iOS 6 I think it was.

Fingers crossed eh! As iOS 10 and WatchOS 3 all look promising and would be gutted to lose homebridge.

Good luck.



On 14 Jun 2016, at 12:12, Sam Turner <notifications@github.com<mailto:notifications@github.com>> wrote:


Well it has been less than 24 hours, so you might have to be a little patient :)

(and don't install a beta on something that you rely on)

-

**Comment by tonesto7** [comment] 2016-06-14 12:50
Mine worked fine until I tried clear the persist cache.  Now it doesn't see it any more. I'm going to setup the bridge again using a low iOS version device.

**Comment by tonesto7** [comment] 2016-06-14 12:52
Also just as an fyi HomeKit allows using a iPad as a home hub. Once turned on it allowed immediate remote access that I could not get working with my AppleTV 3

**Comment by JangoBritt** [comment] 2016-06-14 12:54
I wonder... does iOS 10 allow you to connect to an official HomeKit device? Is it perhaps the whole HomeKit functionality that's borked?

**Comment by tonesto7** [comment] 2016-06-14 13:01
I don't think so the problem seems to be with new discovery's.   Cause it was working great until i tried adding a new platform to homebridge and it failed to start so I had to clear the cache which didn't work so I just removed the homebridge accessory and tried re-adding.

**Comment by JangoBritt** [comment] 2016-06-14 13:08
Could be something related to new Privacy rules written into the HomeKit API... but I'd be surprised if they've made it so different that existing HomeKit devices fail to work

**Comment by tonesto7** [comment] 2016-06-14 13:14
this same thing happened when ios 9 was released and it was resolved in less than 48 hours

**Comment by mattrayner** [comment] 2016-06-14 14:06
I'm not sure if this will help, but I have HomeBridge working on my macOS Sierra machine, and the 'Home' app in iOS 10 can find Homebridge fine?

Thought I'd throw it out there either way

**Comment by bgottsch** [comment] 2016-06-14 16:46
I upgraded my iPhone to iOS 10 which was already configured with homebridge. It's working as expected. Also, I'm using the new "Home" app included in iOS 10.

The new services they added might be a problem, since I can't seem to find a new version of the HomeKit Accessory Simulator app, which contains the UUID of the new services and some info on how the cameras and doorbells work. If there is another source for this info, these services can be easily added.

I did not test a new install by deleting the persist and reseting HomeKit, but will try later. If this is broken, it could be a problem with iOS 10 or it could be a problem with the "Home" app. It's best to also test on the old HomeKit Configurator app, or another from iOS 9.

Still, I don't know if you guys know this, but since iOS 10 is still in beta, there is a non-disclosure agreement, so we best be careful on what we can do.

**Comment by sirago** [comment] 2016-06-14 16:50
Here's what I'm seeing as a user without a persist folder (new setup):

Go to the Home app
Click + then Add Accessory
The search screen appears and my Bridge comes up
Warning message: This accessory is not certified and may not work reliably with Homekit.
Click Add Anyway
Prompted to enter code

If I enter the wrong code, it tells me it's wrong, so I know it's making a connection. 
If I enter the right code, it says "Home could not connect to this accessory."

**Comment by AppleTechy** [comment] 2016-06-14 16:50
It's fine. We are talking to "only" the people who already are running iOS
10. :P It seems to be hit or miss with success of having homebridge work
with iOS 10. My guess is that since it's a beta there is a bug. Before we
make any major investigation to homebridge I suggest we wait until a couple
betas later when it is more stable.

**Comment by bgottsch** [comment] 2016-06-14 16:54
Maybe we could open a branch to work on it, which includes adding the new services and fixing whatever is needed, if it's broken. Since it's a work in progress and many more betas will be released, a branch would be a good place to work until the final version is released.

**Comment by simonrb2000** [comment] 2016-06-14 18:49
Excellent info guys. I'm using homebridge to control my entire house. iOS 10, and watchOS 3 look great and I'd hate to lose homebridge.. And Siri in macOS.. More ways to control my house. Also I think tvOS now supports HomeKit commands but not got the beta to try..



Sent from my iPad

On 14 Jun 2016, at 17:54, Beno <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe we could open a branch to work on it, which includes adding the new services and fixing whatever is needed, if it's broken. Since it's a work in progress and many more betas will be released, a branch would be a good place to work until the final version is released.

-

**Comment by orignboy** [comment] 2016-06-14 23:07
I have been chipping away at homebridge, throughout today with iOS 10 and watchOS3, got the bridge running on my freenas box in a jail, and using nest and sonos plugs to test devices that are not native homekit. I can set temp on my nest, using the apple home app and siri on my watch, so very cool! Sonos best I can manage is to start and stop whatever was playing, as it seems to be tagged as a switch, WIP i guess

**Comment by fedor1210** [comment] 2016-06-14 23:15
We'll not lose HomeBridge. I have no problems using it with iOS 10 and macOS. Just clean "perstent" folder and reset home configuration on your iOS device.

**Comment by mattrayner** [comment] 2016-06-15 15:50
I also got HomeBridge up and running on a Raspberry Pi 3 + Raspbian with the iOS 10 Home app.

I've added my setup steps to this repo incase anyone is interested:
https://github.com/mattrayner/homebridge-config

**Comment by hslewis** [comment] 2016-06-16 01:38
Hi Matttrayner,  I have a Raspberry Pi 2 with Wemo.  (same config as you with no luck getting it working). Any wemo specific configs you needed to do? 

config.json
{
    "bridge": {
        "name": "HomebridgePI",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-156"
    },
    
    "description": "Steves Home Network",

    "platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories" : "0",
          "timeout" : "25",
          "no_motion_timer": "60",
          "homekit_safe" : "1"
        }   
    ]

}

**Comment by AppleTechy** [comment] 2016-06-16 03:09
Try clearing your persist folder as well as the accessories folder. Then
repair, that should work.

**Comment by hslewis** [comment] 2016-06-16 03:57
Just to clarify, I can add Homebridge as an accessory but the Wemo Devices do not show up anywhere.

**Comment by mattrayner** [comment] 2016-06-16 06:18
Increase your expected_accessories number to the number you expect, the
WeMo platform stops looking when it's found the expected number... So if
you search for 0... It'll just proceed

**Comment by pdlove** [comment] 2016-06-16 14:26
For anyone who is having issues with the Wink or Smartthings plugin breaking in IOS 10, please let me know. I did tests this morning starting with clearing the persist and accessories folder in .homebridge and clearing HomeKit on my phone and didn't have any problems, but I know some people have had problems.

**Comment by bgottsch** [comment] 2016-06-16 15:21
Yesterday, Apple released the updated version of HomeKit Accessory Simulator, so now there is a way to find info about how the new accessories work, and their UUID's. Also, they released a video explaining the changes. I watched it, and there are some nice new features which I think will require minor changes to homebridge to be implemented. Since everything is covered by an NDA, it will be hard to discuss about the new features and changes publicly. For those with developer accounts, they updated HomeKit materials in the developer portal, and I believe a new video about a lab will be released today.

**Comment by hslewis** [comment] 2016-06-16 15:29
Thanks Matt,

I changed the expected_accessories setting and see the same output... (assuming thats the log you were talking about). Thoughts?

pi@raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/16/2016, 3:24:38 PM] Loaded plugin: homebridge-platform-wemo
[6/16/2016, 3:24:38 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[6/16/2016, 3:24:38 PM] ---
[6/16/2016, 3:24:40 PM] Loaded plugin: homebridge-wemo
[6/16/2016, 3:24:40 PM] Registering accessory 'homebridge-wemo.WeMo'
[6/16/2016, 3:24:40 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/16/2016, 3:24:40 PM] Homebridge is running on port 51826.

**Comment by mattrayner** [comment] 2016-06-16 16:18
@hslewis have you placed `config.json` inside `~/.homebridge/`? It looks like it hasn't properly read the config file? Try restarting Homebridge again too

**Comment by hslewis** [comment] 2016-06-16 16:26
pi@raspberrypi:~/.homebridge $ ls
accessories  confg.json  persist
pi@raspberrypi:~/.homebridge $ pwd
/home/pi/.homebridge
pi@raspberrypi:~/.homebridge $

**Comment by mattrayner** [comment] 2016-06-16 17:57
clear your accessories and persist folder and restart homebridge

**Comment by hslewis** [comment] 2016-06-16 18:16
Have tried that a few times :). I do have the other wemo plugin installed (homebridge-wemo)  ... no sure if that conflicts.  I am able to successfully register the home bridge platform with the IOS 10 home app but can never see any wemo devices.

**Comment by hslewis** [comment] 2016-06-16 18:25
Hi Matt, I ended up recreating my config.json file and that seemed to fix it. It now discovers the wemo devices. Thanks.

**Comment by jer78** [comment] 2016-06-16 19:09
I'll try the public beta next month. Two questions from people already using the developer beta...

1-does the home app display homebridge accessories or hide them since they aren't authorized?
2-does it break sharing? Seems the last few updates I've had to reset my invitations with my family and rebuild HomeKit from scratch. It's getting annoying! Lol

**Comment by LwsBtlr** [comment] 2016-06-17 06:49
`[6/17/2016, 6:43:03 AM] Loaded plugin: homebridge-kevo
[6/17/2016, 6:43:03 AM] Registering accessory 'homebridge-kevo.Kevo'
[6/17/2016, 6:43:03 AM] ---
[6/17/2016, 6:43:03 AM] Loaded plugin: homebridge-liftmaster
[6/17/2016, 6:43:03 AM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[6/17/2016, 6:43:03 AM] ---
[6/17/2016, 6:43:04 AM] Loaded plugin: homebridge-wemo
[6/17/2016, 6:43:04 AM] Registering accessory 'homebridge-wemo.WeMo'
[6/17/2016, 6:43:04 AM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/17/2016, 6:43:04 AM] Homebridge is running on port 51826.
`

No devices appear on iOS, but I am not sure they are configured right. Not sure how to tell based on this thread.

`    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Dining Room"
        },
        {
            "accessory": "WeMo",
            "name": "Bench"
        },
        {
            "accessory": "WeMo",
            "name": "Bedroom"
        }

    ],

    "accessories": [
      {
        "accessory": "LiftMaster",
        "name": "Garage Door",
        "username": "user",
        "password": "pass"
      }
    ],
    "accessories": [
      {
          "accessory": "Kevo",
          "name": "Front",
          "username": "user",
          "password": "pass"
      }
  ]
`

I put the wrong username in the kevo section, and there is no error or status change when running home bridge manually. Should there be an error?

Also, stupid question on the bridge username, is that a hardcoded MAC address? Should it be my RP's MAC? Is there any consequence to changing the pin as long as it stays 8 numbers?

**Comment by mattcotton** [comment] 2016-06-17 19:21
I'm able to add Homebridge to the new Home app in the iOS 10 Beta - it finds and adds my accessories as devices within Home, but they show as 'No Response'

Is this different to what everyone else is seeing?

**Comment by obstler42** [comment] 2016-06-17 19:24
I had exactly the same experience with ios 10beta1 -- managed to add but all of them show "No Response".

I've also only managed to pair with homebridge once in about 20 or 30 tries -- either doesn't show up at all or can't connect

**Comment by pdlove** [comment] 2016-06-17 21:50
@mattcotton @obstler42 I'm sure y'all picked up on this, but most issues with pairing or not updating are typically caused by an issue with a specific platform.
I suggest you remove platforms until you get it to start working and then post on that platform's issues. It would also be helpful if you post here which platform was found to not work right.
There is a known issue with homebridge-wink associated with locks that is being fixed this weekend.

**Comment by LwsBtlr** [comment] 2016-06-17 22:05
I can pair with Homebridge no problem, but no devices show up. And when device states change (like a memo light comes on) home bridge doesn't report the change, which I'm reasonably sure it did when I set it up before.

**Comment by obstler42** [comment] 2016-06-18 07:22
I tried with homebridge-symcon -- the only platform I have installed. is there a platform that is known to work properly that can be used for testing?

**Comment by Subject22** [comment] 2016-06-18 07:28
Works great with the Lifx platform and iOS 10 beta 1.

**Comment by justme-1968** [comment] 2016-06-18 09:20
i got feedback that homebridge-fhem does also work

**Comment by mattcotton** [comment] 2016-06-18 09:46
@pdlove I only use two platforms - the Nest platform, and one that I wrote myself which is adapted from the LightwaveRF plugin. I'll try removing my own to see whether the Nest one works!

**Comment by entrocode** [comment] 2016-06-19 23:11
@pdlove I just tried switching computers with my old son file (it had been a while since I updated anything) and none of my smart things devices are showing up... Any suggestions?

My config looks like this (not sure if anything has been updated on it lately):

```
{
    "bridge": {
        "name": "KitHome",
        "username": "<MAC ADDRESS>",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
                "platform": "Nest",
                "token": "token",
                "clientId": "id",
                "clientSecret": "secret",
                "code": "code",

                "username" : "username",
                "password" : "password"
        },
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_id": "id",
            "access_token": "token"
        }
    ],
    "accessories": [
        {
            "accessory": "Sonos",
            "name": "Living Room Speakers",
            "room": "Living Room"
        },
        {
            "accessory": "Sonos",
            "name": "Bedroom Speakers",
            "room": "Master Bedroom"
        }
    ]
}
```

**Comment by obstler42** [comment] 2016-06-20 13:10
OK, when I throw out the homebridge-symcon I can at least use homebridge-sonos on IOS10 -- too bad that symcon is the only one I'm really interested in and it is unmaintained for the past half year... Is there some info on what changes might need to be implemented to get a 7-month old unmaintained plugin to work with currend homebridge/ios10?

**Comment by Subject22** [comment] 2016-06-20 19:58
I think there are a few scraps of information floating around. Search the issue tracker, you'll find some useful posts. Hopefully someone more knowledgeable than myself will respond here though 😊 

If you pursue this though you should definitely write up the process. It'd be great to get some up-to-date and thorough documentation on Homebridge! It's a real barrier to entry at the moment, and it'd be great if more people could get involved with the project.

**Comment by obstler42** [comment] 2016-06-21 10:37
alright, even just using the Sonos plugin which basically works fine, there seems to be a problem with IOS10 / Home app. After first opening the home app everything works well, can start/stop the speakers in the app and through Siri. but after some time all the devices just show up with no response, and no way to control them anymore. But force-closing the Home app (swiping it up in the task view) and then starting it again re-enables the devices.

anyone else seeing a similar problem?

**Comment by orignboy** [comment] 2016-06-21 11:04
Hi

Yes I got the same issue, as well with Sonos, they just lock up after a bit. Also control wise using them as a switch is not the most usful thing. Start / Stop and volume control would be better, full control would be the ultimate of course ;)

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Jun 21, 2016 at 11:37 AM +0100, "obstler42" <notifications@github.com<mailto:notifications@github.com>> wrote:


alright, even just using the Sonos plugin which basically works fine, there seems to be a problem with IOS10 / Home app. After first opening the home app everything works well, can start/stop the speakers in the app and through Siri. but after some time all the devices just show up with no response, and no way to control them anymore. But force-closing the Home app (swiping it up in the task view) and then starting it again re-enables the devices.

anyone else seeing a similar problem?

-

**Comment by robertvorthman** [comment] 2016-06-22 13:35
I am unable to pair my iPhone running iOS 10 beta with Homebridge.  I was running Homebridge with iOS 10 beta fine, but then I edited my config.js to add a platform plugin (amazondash).  All my devices became unreachable.  And then a new product appeared in my HomeKit apps, a second duplicate Homebridge bridge, which I added.  Then I had 2 Homebridge bridges in my HomeKit apps.  I finally deleted both Homebridge bridges from HomeKit thinking I could just pair again.  But now when I go to add accessory, my HomeKit apps do not find Homebridge.  Homebridge is definitely running on my Raspberry Pi because I can see it in Bonjour Browser.  I tried simplifying my config.json file to just one accessory, deleting the persist and accessories folder, changing the name and username in config.json, and rebooting everything.  I hope I don't have to reset my HomeKit configuration, it takes hours to set everything up again.

**Comment by jer78** [comment] 2016-06-22 16:30
I'm not running the iOS 10 beta but I found practically every 9.x release this year I had to rebuild my HomeKit and homebridge from scratch (mostly sharing issues with my wife's phone). It's a real pain but I think Apple is making some database changes or something and it's not migrating over nicely. Real PITA. 

I've found the best way to re-pair through trial and error is to 1) shut down homebridge 2) delete the bridge from an iOS app (I mostly used idevices) 3) delete the persist and accessories folder 4) restart homebridge and re-pair. All in that order. If not, usually I had to wipe HomeKit and start over. Something was not clearing correctly.

**Comment by Colton** [comment] 2016-06-23 02:40
Same issue here. Seems like the protocol changed a bit in iOS 10.

**Comment by chokapick** [comment] 2016-06-23 16:51
I've tried to remove and install everything again (Windows 7) and I keep getting the message"Out of Order - The requested device does not conform to Homekit Specifications" on Insteon+.
If I try the new Home app I get "Couldn't Add Accessory".

Everything was working before the IOS 10.

PS: I got the message even with a clean config.

**Comment by aecom** [comment] 2016-06-28 17:13
try to connect home bridge with iOS 9 with your iCloud loved in then all your ios10 devices will work automatically when you open home app assuming you are with the same iCloud

**Comment by totallymystic** [comment] 2016-07-02 20:32
It seems to be working fine for me with SmartThings plugin. Energy meters don't show up though. The Home app has some bugs but I can certainly use Siri and other features. Siri also works with tvOS 10 on my Apple TV to control my homebridge items.

**Comment by totallymystic** [comment] 2016-07-02 20:34
I had to clear my persist folder and cache.

**Comment by chokapick** [comment] 2016-07-07 08:33
By some weird reason my Homebridge was stuck on 2.0 even after several attempts to update or uninstall/install. I notice that today and after removed everything and start all over from scratch I was finally able to add Homebridge to iOS 10 successfully. :)

**Comment by jer78** [comment] 2016-07-08 15:09
I bit the bullet and updated to iOS 10 public beta and homebridge has been working like a charm! I have the Harmony-hub, Netatmo, AppleScriptFile, AppleScriptFileLightbulb and Marantz-Denon plugins and no issues with any of them.

**Comment by apwelsh** [comment] 2016-07-08 16:17
I am using homebridge with only the smartthings plugin.  As such, all my devices tht are supported are exported via a smartthings custom app.  
I just upgraded to iOS 10 public beta 1, and my system is working fine. I have not yet added a new device to my smart home, but it does work with all my connected devices amazingly well.

**Comment by AppleTechy** [comment] 2016-07-08 16:33
If you neee help please message me on slack. It is hard to address the variety of problems that could be causing this problem for homebridge users on iOS 10. My username is "applegeek" on Slack, message me the specific error code you are getting as well as what you have tried to resolve the problem and what plugins you are running.

**Comment by irrg** [comment] 2016-07-10 18:42
I'm fixing up my setup right now…cleared persist, but uhm… 'reset configuration' has disappeared from my homekit section in settings > privacy. Anyone else see that? (Or, rather, doesn't see that)

**Comment by jer78** [comment] 2016-07-10 18:44
It's in the Settings > Home now

**Comment by malixsys** [comment] 2016-07-16 15:47
My iOS 10 iPhone can see the kitchen light just fine away from my home network with my AppleTV 3rd gen plugged in...
I used the MyTouchHome app to configure the network. Homebridge runs on mac mini upstairs

**Comment by Colton** [comment] 2016-07-17 22:09
This issue should probably be closed. Seems that most of the problems are not caused by Homebridge, but with iOS 10 as a platform.

**Comment by driskell** [comment] 2016-07-23 12:10
Works great for me on pub beta 2. But I did have to open the firewall on the machine running homebridge.

**Comment by andig** [comment] 2016-07-25 09:30
> I bit the bullet and updated to iOS 10 public beta and homebridge has been working like a charm

My problem: it used to work once. Right now, I can only get homebridge working in homekit if I remove and re-add the bridge. After that, if I ever restart homebridge, homekit will get stuck with "bridge/device" not responding messages until I delete the bridge again.

Homebridge debugging shows that the pairing is actually happening. Has anyone seen this behaviour?

> I'm fixing up my setup right now…cleared persist, but uhm… 'reset configuration' has disappeared from my homekit section in settings > privacy. Anyone else see that?

> It's in the Settings > Home now 

I'll yet have to test yet if this helps.

**Comment by emeshuris** [comment] 2016-07-30 04:56
When I upgraded from beta 1 to beta 2, it seemed to not work.
I don't remember exactly what I did, but I removed my home from home, I believe that I uninstalled the home app (ios 10 lets you uninstall stock apps) and reinstalled from the store.
After that, although I had to recreate my setup, everything has been solid.
btw, I've been on the beta since the first week.

**Comment by kylewill** [comment] 2016-08-13 17:56
I tried setting up and was finally able to get the Home app to recognize HomeKit (required hiding the "locks" group within Wink". I'm getting the "No Response" issue though. 

Has anyone gotten working on the latest Beta (4)?

Also weird, during the "Add Accessory" phase after adding Homebridge I had to hit "next" with each Wink accessory repeated several times.

**Comment by andig** [comment] 2016-08-13 21:58
Wfm using homebridge-fritz on beta 4. Seeing no response messages though. 

Viele Grüße,
Andreas

**Comment by driskell** [comment] 2016-08-21 12:36
I'm on latest beta and not having any issues. Though we did actually add it via iOS 9 and I'm just with "shared" access. But things do respond great. Maybe those with issues could post your homebridge plugins and versions and also what type of machine it running on (Pi / PC / Mac). Last time I had no response issues it had either crashed or firewall had lost it's open port.

**Comment by pdlove** [comment] 2016-08-21 13:55
@kylewill I think the Wink locks have a minor issue that did not affect the older IOS releases.
I was working on an update to the Wink plugin to allow streaming the updates from wink rather than polling in order to support version 2 keys but got distracted due to my hub being finicky and the question coming up on how to link cameras to HomeKit through HAP-NodeJS. 
Ultimately I think I just need to get a new hub as mine has been experimented on far too much.
I second what driskell said... Anyone with issues needs to post the type of machine and all plugins you're using. For the bridge-type plugins like Wink and Smartthings it is also helpful to know what types of devices you have.
I'd say 9 out of 10 times an IOS upgrade doesn't work with homebridge, it's due to one or more plugins.

**Comment by mriksman** [comment] 2016-09-13 23:05
@pdlove Hey I just went to iOS 10, and only use Nest and Wink plugins. I notice the Home app isn't behaving very well; always saying 'No Response', but if I click on it, it eventually updates and will eventually control. Scenes say 'Failed', but will run.

Seems to be an issue with status updates?

Used to work fine on iOS 9 and using the Eve app. I could just ask Siri to open my blinds, or change the colour of my lights etc. no problem.

Would love to get these bugs ironed out for Wink and the Home app.

**Comment by pdlove** [comment] 2016-09-13 23:32
@mriksman I'm not sure, my Wink hub quit working reliably about 4 months ago and I haven't been able to get it replaced so I haven't had a way to properly test it with IOS 10.
I do know we originally had issues with Siri timing out and found that happy medium. It sounds like she's finally decided enough is enough and slow responses will be ignored. :)
Let me order a replacement Wink hub and then I'll do some work again on the Pubnub enhancement to get updates in real time.
Anyone know a cheap source for Wink Hubs?

**Comment by mriksman** [comment] 2016-09-13 23:43
@pdlove If you think you can make the Wink plugin work reliably, I'll pay/send you a Wink hub... 

Regards,

Michael Riksman

**Comment by mriksman** [comment] 2016-09-13 23:46
Just spoke with someone on the Wink forum, they are having zero problems. 
Trust me to have the issues!!

Regards,

Michael Riksman

**Comment by pdlove** [comment] 2016-09-13 23:53
@mriksman It's always hit or miss with the complete platforms like Wink and smart things. It's mostly about the mix of devices you have.
Have you tried disabling the locks group? That has worked for a few other people.
I've got my hub on order. I'll move some locks, lights and a thermostat over to it when I get it setup again. It'll be nice to be able to control my lutron switches and smoke detectors again.

**Comment by mriksman** [comment] 2016-09-14 08:25
It could be my Somfy blinds. When all the devices show 'No response', I can click the 'i' incon, and the status will immediately refresh. Except my blinds. They go back to 'Updating', and eventually 'No response' again. There is no feedback from these blinds; but I thought that wouldn't matter with the homebridge-wink code. 

I may have messed around with the code. I'll have to take a look.

**Comment by ajl236** [comment] 2016-09-14 08:55
I just upgraded to iOS10 on iPhone and homebridge (on Ubuntu Server ) showed no accessories listed until removing the persist directory and restarting the homebridge service

**Comment by affrae** [comment] 2016-09-14 09:42
Hi. I know his may not help. Just wanted to report that I have had no issues since updating to iOS 10. I am only using homebridge to provide HomeKit access to my LIFX lights.

**Comment by mriksman** [comment] 2016-09-14 12:18
It appears to be the shades/blinds. The lock is fine. As soon as I hide the group 'shades', the Home app responds nicely. Anyone have shades?

**Comment by mriksman** [comment] 2016-09-14 13:15
I'm looking at Wink@Home and the last_reading.position is null. I bet that's the issue. Even the desired_state.position is null shortly after I issue a command. i have it partially working; i've avoided the app setting everything to 'No Response' by setting the 'get' commands to arbitrarily always return 0, but it still gets a little upset.

**Comment by irrg** [comment] 2016-09-14 14:56
It might be wise to move all the Wink stuff to a separate issue? This one is kind of a catch-all and people without Wink hardware have nothing to contribute here. I know I could unsubscribe from this issue but greater (homebridge-notaplugin level) issues are actually interesting and relevant to me so I'd rather stay subscribed.

**Comment by cybertza** [comment] 2016-09-14 21:54
I just installed fresh as per guide, only thing I had to change was the /usr/local path for the service file to /home/pi/HomeKitbridge/bin/HomeKit and now my service auto starts, added 8 http , imported fine,  working perfectly. 👍🏻 Great work.

**Comment by mriksman** [comment] 2016-09-14 23:18
Anyone able to provide advice on the following?

When Homebridge makes the 'set' call on Characteristic.TargetPosition, i need to save that value. Then, when a 'get' is made on Characteristic.TargetPosition or Characteristic.CurrentPosition, i just want to feed that value back. 

How can I 'save' a value in HomeBridge javascript?

**Comment by chgorsan** [comment] 2016-09-15 13:57
Does anyone have any luck making Wemo Devices work? Mine are recognized but seem non-responsive.

**Comment by n8man** [comment] 2016-09-16 20:24
@pdlove @mriksman I'm also using homebridge-wink and had an issue pairing unless I disabled the locks group. After that I was able to pair but would run into the 'No response' issue. With locks disabled I tested every permutation of groups and continued to have the same 'No response' issue. I saw what @robertvorthman wrote here: https://github.com/KraigM/homebridge-wink/issues/49 about switching to the old leaked Wink client/secret IDs (instead of using the IDs provisioned to me), and to my surprise it all started working, locks and all.

**Comment by kennymatic** [comment] 2016-09-17 05:06
@chgorsan I just reinstalled everything (nodejs/homebridge/homebridge-platform-wemo) and cleared out the ~/.homebridge/persist folder as suggested and finally everything came up in the iOS10 Home app. Everything seems to work as expected.

**Comment by chgorsan** [comment] 2016-09-17 05:33
@kennymatic I did the same and at first it didn't want to work, but now I got back home and it started working out of nowhere!!! Haha thanks!

**Comment by nrobinson2000** [comment] 2016-09-18 03:15
I setup Homebridge on my RPi today.  It works perfectly in iOS 10.  Keeping the config.json valid is hard, but I live having my Particle devices and IFTTT available in the home app.

**Comment by TheChallinor** [comment] 2016-09-18 08:11
Hey, literally all my home devices are linked to IFTTT, have you setup IFTTT maker channel for each one to turn on / off, arm, disarm, etc? 

So far I've only got Nest working with homebridge.

**Comment by nrobinson2000** [comment] 2016-09-18 14:51
>  Have you setup IFTTT maker channel for each one to turn on / off, arm, disarm, etc?

Yes, that is how the [homebridge-ifttt plugin](https://github.com/ilcato/homebridge-ifttt) works.  [Here is my config.json for using Particle and IFTTT (credentials removed).](https://gist.github.com/nrobinson2000/714400c4184eff7628b499ae0348e4c6)

I basically had to create two `platform` blocks in my `config.json` in order for both platforms to work.

**Comment by pjs1234** [comment] 2016-09-30 20:58
hi help me 
homebridge is 2 location 
 usr/local/lib/node_modules/homebridge
 Users/palle/.homebridge/

config.json (/Users/pallejuulsorensen/.homebridge/config.json) not found. usr/local/lib/node_modules/homebridge config-sample.json

**Comment by erpeters3** [comment] 2016-10-09 00:24
iOS 10 iPhones cannot add Homebrisge running on Sierra. Always receive the "cannot add this accessory" error. No joy. Did a full reinstall of node through Vera plugin and deleted the two folders recommended. Rebuilt config.json from scratch using Atom to avoid undesired artifacts. No joy. Any troubleshooting tips??

**Comment by grstreten** [comment] 2016-10-11 20:06
Also having the same issue as @erpeters3. Nightmare! Going to try this on another device running as a server instead, but definitely something which is a pain.

**Comment by EMCSizl** [comment] 2016-10-15 21:23
Had a similar message when adding . Deleted my entire Home In IOS and removed persists files but no change. 
Repeated the above and changed the Username in config.json (just changed 1 number)and this allowed me to add the bridge.

**Comment by erpeters3** [comment] 2016-10-15 21:41
Resolved my issue. I think I had a Hue recursion issue. Had the Hue added to Vera and as an accessory. I disabled all Hue devices and hoila. Perfect.

**Comment by erpeters3** [comment] 2016-10-16 12:17
To clarify. I disabled all Hue devices created on Vera by the Hue plugin/addon to Vera. This excludes them from Homebridge-Vera launch.

**Comment by ngiles** [comment] 2016-10-27 18:47
New to homebridge. Seems like the server is working but I cannot see any accessories on iDevice running Home app to add accessories. Here is what I see on the server:

[10/27/2016, 11:16:12 AM] Loaded plugin: homebridge-http-simple-switch
[10/27/2016, 11:16:13 AM] Registering accessory 'homebridge-http-simple-switch.SimpleHttpSwitch'
[10/27/2016, 11:16:13 AM] ---
[10/27/2016, 11:16:13 AM] Loaded config.json with 1 accessories and 0 platforms.
[10/27/2016, 11:16:13 AM] ---
[10/27/2016, 11:16:13 AM] Loading 1 accessories...
[10/27/2016, 11:16:13 AM] [Corner Lamp On] Initializing SimpleHttpSwitch accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
│ 123-45-678 │
[10/27/2016, 11:16:13 AM] Homebridge is running on port XXXXX.

Changed pairing code and port for security considerations.

Here is my config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "123-45-678"
    },

    "description": "Home Control",
    	"accessories": [
        {
            "accessory": "SimpleHttpSwitch",
            "name": "Corner Lamp On",
	    "url": "http://192.168.X.X/WebAppFileName.jsp?device=a2&state=on",
	    "sendimmediately": "",
	    "http_method": "GET"
        }
    	]	
}

Username/port/pin/IP Address modified for security. Does it really matter what goes in the Bridge username and port fields?

Advice?

**Comment by h00pak** [comment] 2016-11-21 12:23
Hi ngiles, I absolutely had to have something that looked like a MAC address in the username and a port number. I got those from my Nest thermostat developer account. As soon as I changed that information, I could connect to home bridge from the Home app. Hope that helps.

**Comment by iksaku** [comment] 2017-01-15 03:27
Is this "issue" still relevant to be open? Homebridge  actually works perfectly with iOS 10 (if well configured with plugins)

**Comment by KhaosT** [comment] 2017-01-15 04:11
Yeah I think this one can be closed now.

**Closed by KhaosT** 2017-01-15 04:11 UTC
