### ISSUE TITLE
Verify Fail Layer Decrypt Error

### ISSUE THREAD

**Issue by jsg4** [nfarina/homebridge#791] opened 2016-09-22 23:44 UTC
Seeing this error after running for a day or two every time. Anyone know? Happens on macOS and Raspberry Pi.

http://pastebin.com/J56BdKJe

**Comment by jonferreira** [comment] 2016-09-24 14:42
I'm seeing the same too! my money is it somehow related with iOS10 as this started happening only after I upgrade

**Comment by rehafer** [comment] 2016-09-24 16:22
Same here. Updated to iOS 10 recently. I restarted this morning again before I left for work; should've copied the error messages and posted them but in a hurry.

**Comment by KhaosT** [comment] 2016-09-24 17:23
Interesting, how many accessories do you have in homebridge?

**Comment by jsg4** [comment] 2016-09-24 17:25
About 65-70 for me.

**Comment by KhaosT** [comment] 2016-09-24 17:53
When you experience that error, were you trying to run a scene or something?

**Comment by rehafer** [comment] 2016-09-24 18:01
I notice that Homebridge has stopped working when I try to use the Home app and it can't find any Homebridge devices; the I VNC into the server and restart. I've never noticed it quitting while using the app. I am using Indigo with about 70 devices many of which are running on triggers or schedules.

**Comment by jonferreira** [comment] 2016-09-24 18:03
pretty much the same here...i have no idea what causes it to crash, i have about 60 devices there but I don't even bother using Home App, I mainly use for quick access to favourite devices (9). all I can say is out of the blue they stop updating status and homebridge crash

**Comment by rehafer** [comment] 2016-09-24 18:09
I wonder if this is connected to the iOS 10 battery issue. I notice that Siri is using a high percentage of battery, always in the top 3

**Comment by KhaosT** [comment] 2016-09-24 18:10
Okay... I do see this error when doing pressure test with HomeKit with a lot accessories...It appears to be random but as long as HomeKit tries to write a lot commands in the same time (aka run a scene/trigger), there is a rare chance it will corrupt the data it tries to send. not really sure why...

**Comment by jsg4** [comment] 2016-09-24 18:22
Using it with homeassistant, the scenes are exposed as switches so running a scene to HomeKit is only turning on one device. Would that still cause this issue?

**Comment by KhaosT** [comment] 2016-09-24 18:23
That shouldn't ... it should only happen with large message payload.

**Comment by jsg4** [comment] 2016-09-24 18:25
Right but what I'm saying is I do not use HomeKit to control multiple devices at the same time, just a device every now and then. Makes it even stranger!

**Comment by KhaosT** [comment] 2016-09-24 18:26
Huh... would you mind to run homebridge under debug mode ``DEBUG=* homebridge`` and when this occurs again, post the last few lines at here so I can figure out what's wrong...

**Comment by jsg4** [comment] 2016-09-24 18:28
Sure thanks man

**Comment by rehafer** [comment] 2016-09-24 18:59
I've noticed that my Z-wave devices tend to "poll" all at once. I'm going to start watching that in connection with Homebridge

**Comment by jsg4** [comment] 2016-09-26 01:05
@khaost here is latest error with logging

http://pastebin.com/bFWibcmj

**Comment by KhaosT** [comment] 2016-09-26 01:14
It doesn't look like there is an layer decryption error here…

**Comment by jsg4** [comment] 2016-10-01 00:08
@khaost what about this?

http://pastebin.com/yxPTBR5k

**Comment by jsg4** [comment] 2016-10-07 21:50
@KhaosT

More errors here http://pastebin.com/6GSKS94L

**Comment by dgburton** [comment] 2016-10-08 08:41
I'm also seeing this regularly:

```
[10/8/2016, 7:45:49 AM] [Indigo Server - Main House] Gate: getPosition() => 0
[10/8/2016, 7:45:49 AM] [Indigo Server - Main House] Indigo request: http://127.0.0.1:8176/devices/Gate.json
[10/8/2016, 7:45:49 AM] [Indigo Server - Main House] Gate: getPosition() => 0
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
undefined:1
{"characteristics":[{"aid":59,"iid":11,"ev":true},{"aid":59,"iid":14,"ev":true},{"aid":60,"iid":11,"ev":true},{"aid":60,"iid":14,"ev":true},{"aid":61,"iid":11,"ev":true},{"aid":61,"iid":14,"ev":true},{"aid":62,"iid":11,"ev":true},{"aid":62,"iid":14,"ev":true},{"aid":63,"iid":11,"ev":true},{"aid":63,"iid":14,"ev":true},{"aid":64,"iid":11,"ev":true},{"aid":64,"iid":14,"ev":true},{"aid":65,"iid":11,"ev":true},{"aid":65,"iid":14,"ev":true},{"aid":66,"iid":11,"ev":true},{"aid":66,"iid":14,"ev":true},{"aid":67,"iid":11,"ev":true},{"aid":67,"iid":14,"ev":true},{"aid":68,"iid":11,"ev":true},{"aid":68,"iid":14,"ev":true},{"aid":69,"iid":11,"ev":true},{"aid":69,"iid":14,"ev":true},{"aid":70,"iid":11,"ev":true},{"aid":70,"iid":14,"ev":true},{"aid":71,"iid":11,"ev":true},{"aid":71,"iid":14,"ev":true},{"aid":72,"iid":11,"ev":true},{"aid":72,"iid":14,"ev":true},{"aid":73,"iid":11,"ev":true},{"aid":73,"iid":14,"ev":true},{"aid":74,"iid":11,"ev":true},{"aid":74,"iid":14,"ev":true},{"aid":75,"iid":11,"ev":true},

SyntaxError: Unexpected token 
```

**Comment by justme-1968** [comment] 2016-10-10 08:35
saw the same for the first time this weekend

**Comment by jsg4** [comment] 2016-10-15 12:00
Here's another log in case this helps 

http://pastebin.com/ZV8fEFha

**Comment by jonferreira** [comment] 2016-10-18 12:06
I'm also getting same errors, happens every now and then for no apparent reason

```[10/18/2016, 8:41:26 AM] [eDomoticz] MQTT Message received for Living Room Yellow Light.
Name:           Living Room Yellow Light
Device:         Light/Switch,Switch
Is Switch:      true
SwitchTypeVal:  7
MQTT Message:
{
    "Battery": 255,
    "RSSI": 12,
    "dtype": "Light/Switch",
    "id": "00000A01",
    "idx": 138,
    "name": "Living Room Yellow Light",
    "nvalue": 2,
    "stype": "Switch",
    "svalue1": "49",
    "switchType": "Dimmer",
    "unit": 1
}
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!

```

**Comment by humac** [comment] 2016-10-24 03:27
I'm seeing this issue as well. I'm running on raspberry pi.  I'm running Netatmo, SmartThings and harmonyhub plugins.  Home bridge runs for a few hours then i see this error.

error at req:  getaddrinfo ENOTFOUND graph.api.smartthings.com graph.api.smartthings.com:443
error at req:  getaddrinfo ENOTFOUND graph.api.smartthings.com graph.api.smartthings.com:443
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
undefined:1
{"characteristics":[{"aid":6,"iid":24,"ev":true},{"aid":6,"iid":27,"ev":true},{"aid":2,"iid":27,"ev":true},{"aid":2,"iid":30,"ev":true},{"aid":3,"iid":19,"ev":true},{"aid":3,"iid":22,"ev":true},{"aid":4,"iid":18,"ev":true},{"aid":4,"iid":21,"ev":true},{"aid":5,"iid":26,"ev":true},{"aid":5,"iid":29,"ev":true},{"aid":7,"iid":16,"ev":true},{"aid":7,"iid":19,"ev":true},{"aid":8,"iid":16,"ev":true},{"aid":8,"iid":19,"ev":true},{"aid":9,"iid":16,"ev":true},{"aid":9,"iid":19,"ev":true},{"aid":10,"iid":14,"ev":true},{"aid":10,"iid":17,"ev":true},{"aid":11,"iid":10,"ev":true},{"aid":11,"iid":13,"ev":true},{"aid":12,"iid":16,"ev":true},{"aid":12,"iid":19,"ev":true},{"aid":13,"iid":18,"ev":true},{"aid":13,"iid":21,"ev":true},{"aid":14,"iid":16,"ev":true},{"aid":14,"iid":19,"ev":true},{"aid":15,"iid":16,"ev":true},{"aid":15,"iid":19,"ev":true},{"aid":16,"iid":14,"ev":true},{"aid":16,"iid":17,"ev":t
                                                                                                              

SyntaxError: Unexpected token

**Comment by KhaosT** [comment] 2016-10-24 04:01
It looks it always occur when HomeKit tries to write a lot of data to bridge... not really sure why though 🤔

**Comment by jonferreira** [comment] 2016-11-03 15:20
could it be related with the log file size? I've jsut noticed mine is 560mb!

**Comment by KhaosT** [comment] 2016-11-03 16:12
not really. This occurs when iOS tries to write to homebridge, there is nothing to do with logs.

Best Wishes,
Tian Zhang

**Comment by jonferreira** [comment] 2016-11-03 16:13
back to square one then...I've just added a node-red flow to tail the logs and restart homebridge when this happens, should be enough while this gets sorted
best of luck!

**Comment by anthonywebb** [comment] 2016-11-09 05:13
I am seeing the same thing now.  I have 95 accessories on my cbus platform plugin 
https://gist.github.com/anthonywebb/ad83426779f6d087b15b410cf9f91651

This is running on a pretty beefy mac, and spewed out when I unlocked my phone (was unlocking to the home screen, not to the "home" app).. any ideas?

**Comment by KhaosT** [comment] 2016-11-09 05:15
@anthonywebb would you mind update homebridge to latest (v0.4.8) and when this occurs again, post the content of ``Packet: `` at here?

**Comment by anthonywebb** [comment] 2016-11-09 05:17
I am running 0.4.8, just installed a couple hours ago @KhaosT

**Comment by KhaosT** [comment] 2016-11-09 05:18
Okay so when this occurs again, you should see an error message + a huge chunk of data printed in your log/console. Please post that here.

**Comment by anthonywebb** [comment] 2016-11-10 01:37
@KhaosT here is the detail from my latest crash.  Man this is nasty, cant stay up for more than 10 or 15 minutes.

https://gist.github.com/anthonywebb/65505cae159f9a59535665fb3579526d

**Comment by KhaosT** [comment] 2016-11-10 01:49
@anthonywebb thanks! this is really helpful. So the problem is the data got split into multiple packets and that's not what the program is expecting. I'll try to fix it soon.

**Comment by KhaosT** [comment] 2016-11-10 02:12
@anthonywebb please give homebridge v0.4.9 a try and see if this issue still occurs. Thanks!

**Comment by anthonywebb** [comment] 2016-11-11 05:47
@KhaosT you seemed to have fixed this issue, I have been running solid ever since (24+ hrs), before I was crashing every 20 minutes.  Nice fix!

**Comment by KhaosT** [comment] 2016-11-11 06:59
Glad to know. I'll close the issue for now and if you see the similar problem in the future, please open another one. Thanks!

**Closed by KhaosT** 2016-11-11 06:59 UTC
Labels: bug

**Comment by jonferreira** [comment] 2016-11-15 08:25
I was having the same problem so I've updated homebridge to v0.4.9 but immediately started having the above error

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 877adcba-08f0-4ed4-9f76-e5ab6e4d4938
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:206:41)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:1082:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)

```

**Comment by jonferreira** [comment] 2016-11-15 08:37
OK I got it working by temporarily remove one device but this doesn't explain why it started to happen. How is the above UUID generated? does it have anything to do with the device name?

I had 2 devices with same name and that's what seemed to be cause the above problem.

**Comment by KhaosT** [comment] 2016-11-15 08:41
@jonferreira please contact the author of ``homebridge-edomoticz`` for this problem. The plugin is expected to provide a unique id for each accessory.

**Comment by jonferreira** [comment] 2016-11-15 08:48
will do. please notice though that the *only* change I've made in weeks was the update to v0.4.9...those 2 devices have been there for as long as I remember and I've not touched anything else.
Thanks

**Comment by KhaosT** [comment] 2016-11-15 08:48
i didn't make any changes in this area so not really sure why this is happening.

**Comment by jonferreira** [comment] 2016-11-15 08:49
strange, I'll contact him though
