### ISSUE TITLE
Events.js:141 Unhandled Exception

### ISSUE THREAD

**Issue by realdannys** [nfarina/homebridge#408] opened 2015-11-29 02:03 UTC
Homebridge crashes out after running for a while for me with the follow error. I'm presuming its not plugin related.

    events.js:141
      throw er; // Unhandled 'error' event
      ^

    Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:544:26)

Running on OS X 10.10 Server

**Comment by jclarke0000** [comment] 2015-12-20 01:36
Seeing a similar error, after HomeBridge runs for a few days.  Have seen this twice now.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 50.16.21.11:443
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

**Comment by IMNotMax** [comment] 2016-01-03 00:40
Did you use homebridge-ssh ? I have a similar issue and it's caused by this plugin

**Comment by jclarke0000** [comment] 2016-01-03 00:51
@IMNotMax No I haven't used that plugin. But I recently upgraded to the latest version of the HomeBridge-nest plugin. So far so good.

**Comment by rudders** [comment] 2016-01-06 05:12
Suggest running with debug enabled so you can track down the plugin that's not handling the error.

`env DEBUG=* homebridge`

**Comment by AppleTechy** [comment] 2016-01-08 00:31
I am still running into this issue even after the newest update

**Comment by AppleTechy** [comment] 2016-01-08 00:57
The last couple lines when running in debug mode are
Current humidity for Office is: 35%
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT (My ip)
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by jclarke0000** [comment] 2016-01-08 01:54
Did you also update to use the new cloud API for Nest? That might be what fixed this for me.

**Comment by AppleTechy** [comment] 2016-01-08 01:57
@jclarke0000 I did update to the new Cloud API

**Comment by jclarke0000** [comment] 2016-01-08 02:04
There was also a point release for HomeBridge to 0.2.13 as well.  That's the only other change I made, and it's been running stable ever since.

**Comment by AppleTechy** [comment] 2016-01-08 02:08
@jclarke0000 I also have installed the newest release of home bridge and it definitely takes it less than a couple days to show the issue

**Comment by rudders** [comment] 2016-01-08 02:20
I have a quick look at the nest plug-in and I'm not sure it is capturing all of the potential errors. It uses request-promise which I'm not very familiar with. I was going to make some comments on that plug-in and see if that gave any clues.

**Comment by erfinb** [comment] 2016-01-13 00:30
I'm still having the same issue as well.  I get the following crash and am using the new Nest API, the new WEMO platform, and newest version of HomeBridge.

--------------------------------------------------------
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.0.1.14:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by realdannys** [comment] 2016-01-13 00:33
To be honest, i'm not even sure if I still have this, it doesn't really matter as I have HomeBridge automatically kept alive if it crashes so it doesn't really affect my usage anymore. But there's obviously some error not being handled. For the record I don't use any of the plugins mentioned here, so its not related to Nest, SSH, or any updated or older version of HomeBridge either.

**Comment by erfinb** [comment] 2016-01-13 00:35
How are you keeping it alive if it crashes 🙂?

**Comment by rudders** [comment] 2016-01-13 05:35
I am trying to track down a similar / this problem over at https://github.com/rudders/homebridge-platform-wemo/issues/21 it certainly looks like the (well my) `homebridge-platform-wemo` that may be the issue with an uncaught error in `wemo-client` but I only had one person report it. @realdannys and @erfinb can you confirm you are having this issue still 
 - have you (could you please) updated to `homebridge-platform-wemo@0.6.4` to see if the problems persist.

**Comment by uchuujin** [comment] 2016-01-13 14:31
@erfinb I do the same thing as @realdannys by putting "homebridge" in a shell script.  You can use this if you like.  Some of this is now redundant since @rudders added the "homekit_safe" option.  If you're on 0.6.4, you could remove the while "if [ "`grep ...]; then" loop.  Whatever value you put for "sleep" should be slightly longer that the timeout for "homebridge-platform-wemo" in your config. file

#!/bin/bashwhile true
do
	rm -f ~/.homebridge/homebridge.log
	echo "Starting:  `date`" >~/.homebridge/homebridge.log
	echo "---"   >>~/.homebridge/homebridge.log
	homebridge   >>~/.homebridge/homebridge.log &
	tail -n 999 -f ~/.homebridge/homebridge.log &
	sleep 15
	if [ "`grep 'We have timed out and only discovered' ~/.homebridge/homebridge.log`" != "" ]; then
		echo "------------------------------------------"
		echo "Restarting due to device discovery failure"
		echo "------------------------------------------"
		pkill homebridge
		pkill tail
	fi
	wait `pgrep homebridge`
	pkill tail
done

**Comment by uchuujin** [comment] 2016-01-13 14:32
Unfortunately, this site removes the indentation that makes it a bit easier to read... :(

**Comment by uchuujin** [comment] 2016-01-13 14:34
Arghhhh... and you need to have the backward apostrophe around the bits that show up in gray.  This site is not to great on formatting... Or I don't know how to use it.

**Comment by snowdd1** [comment] 2016-01-13 15:00
You might want to use four backward apostrophes before and after your pre-formatted text.

**Comment by uchuujin** [comment] 2016-01-13 15:02
Thanks! Actually, I edited that post and found that I could to put a backslash in front of it and it comes out ok.

**Comment by snowdd1** [comment] 2016-01-13 15:07
If you a language identifier it could look like
````shell
#!/bin/bash
while true
do
rm -f ~/.homebridge/homebridge.log
echo "Starting: `date`" >~/.homebridge/homebridge.log
echo "---" >>~/.homebridge/homebridge.log
homebridge >>~/.homebridge/homebridge.log &
tail -n 999 -f ~/.homebridge/homebridge.log &
sleep 15
````

Using 
\`\`\`\`shell 
as the first line. Hard to type on an iPhone I have to admit.

**Comment by uchuujin** [comment] 2016-01-13 15:09
Ah... That cool.  I'll try to edit that post again and see what I get.

Thanks!

**Comment by snowdd1** [comment] 2016-01-13 15:10
Welcome! Have you seen the Preview tab?

**Comment by realdannys** [comment] 2016-01-13 15:11
Id just like to add that I don't use shellscripts. I'm running OS X and I just load Homebridge at launch with a simple plist in my user launchagents folder that keeps the program alive when it crashes and logs outputs and errors to the console.

**Comment by erfinb** [comment] 2016-01-13 15:13
Could you tell me how you also do that Dan?

**Comment by erfinb** [comment] 2016-01-13 15:13
Thank you all so much for the ideas!

**Comment by realdannys** [comment] 2016-01-13 15:16
Its all here, just create a .plist in your users launchagent folder and put that info in.

https://github.com/nfarina/homebridge/issues/316#issuecomment-163598087

**Comment by uchuujin** [comment] 2016-01-13 15:16
@snowdd1 Yes, I saw Preview.  I just didn't know how to change the formatting.

@realdannys Actually, I'm on OS X, too.  A "plist" is also a good idea, but I'm going to wait until things settle down a bit.  At the moment, the only way I can get "homebridge" to stay stable is to run @rudders' unofficial 0.6.3 version of "wemo-client".  That works just fine for me, but the official version won't stay up more than 3 or 4 hours.

**Comment by rudders** [comment] 2016-01-13 18:42
Anyone experiencing `ETIMEDOUT` errors and that use the `homebridge-platform-wemo` plugin might like to test my forked version of the plugin discussed here https://github.com/rudders/homebridge-platform-wemo/issues/21#issuecomment-171392046 - please update that issue with your findings.

**Comment by erfinb** [comment] 2016-01-15 21:20
Okay, so I have tried the script to make sure that HomeBridge is always running and have also tried a few other ideas.... still getting the error:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.0.1.16:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

Any ideas? The computer running is connected over WiFi... could this be an issue?

**Comment by IMNotMax** [comment] 2016-01-16 03:31
Hi @erfinb, see the wiki:https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#notes
It should help even if you are on a regular linux (not a arm version) :)

**Comment by kenderson** [comment] 2016-01-24 00:30
Same issue here - been fighting this one for a few weeks now. 

I've been pulling each of the components out one at a time to see if it's related to HW, or something in the code. Thus far, it seems to not be specific to any HW component.

**Suggestions welcome!**

In my set-up, I use;
* homebridge-nest
* homebridge-platform-wemo
* homebridge-wemo
* Running this on OS X (10.11.3)

And it tells me that all of the legacy plugins are loaded as well. .

Below are a few examples of the Error.
**Example 1**
```
Setting target temperature for Upstairs to: 71
Target temperature for Upstairs is: 71 F
Target temperature for Upstairs is: 159.8 F
Target temperature for Upstairs is: 71 F
Current heating for Upstairs is: 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.6:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```
**Example 2**
```
Setting target temperature for Upstairs to: 71
Target temperature for Upstairs is: 71 F
Target temperature for Upstairs is: 159.8 F
Target temperature for Upstairs is: 71 F
Current heating for Upstairs is: 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.6:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```
**Example 3**
```
[WeMo Platform] Office Fan binaryState: 0
Current temperature for Upstairs is: 70 F
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 192.168.1.5:49153 - Local (0.0.0.0:56726)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:939:9
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
**Example 4**
```
Current temperature for Upstairs is: 70 F
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.9:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```
**Example 5**
```
Current heating for Upstairs is: Heating
Target temperature for Upstairs is: 71 F
Current humidity for Upstairs is: 40%
Current temperature for Upstairs is: 71 F
Current heating for Upstairs is: 0
Current temperature for Upstairs is: 70 F
Current heating for Upstairs is: Heating
Current temperature for Upstairs is: 71 F
Current heating for Upstairs is: 0
Current temperature for Upstairs is: 70 F
Current heating for Upstairs is: Heating
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.6:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```
**Example 6**
```
[WeMo Platform] Living Room Light binaryState: 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.9:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

Current temperature for Upstairs is: 69 F
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.6:49153
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by rudders** [comment] 2016-01-24 03:52
Suggest you track https://github.com/rudders/homebridge-platform-wemo/issues/21
specifically the instructions in this comment (from me) https://github.com/rudders/homebridge-platform-wemo/issues/21#issuecomment-171392046 will lead you to a debug/beta version that might help.

**Comment by rudders** [comment] 2016-01-24 03:53
Also suggest you move away from `homebridge-wemo` as it's not being maintained like `homebridge-platform-wemo`

**Comment by kenderson** [comment] 2016-01-24 04:00
@rudders Appreciate the link to the other thread!

I needed to keep the original Wemo in there, as the platform wasn't recognizing my Wemo maker. Otherwise, I'd love to consolidate down. If you think it should recognize a maker, let me know, and I'll run some tests!

Thanks again!

**Comment by rudders** [comment] 2016-01-25 02:45
We could probably add the maker pretty easily - what services does it offer do you know?

**Comment by rudders** [comment] 2016-01-27 20:46
@kenderson - Issue for adding Maker Support - https://github.com/rudders/homebridge-platform-wemo/issues/28

**Comment by rudders** [comment] 2016-01-27 20:48
Latest test version of homebridge-platform-wemo is available for anyone getting these errors from wemo platform. Will be pushed to released version this weekend I hope.

Refer instructions for testing and rollback [here](https://github.com/rudders/homebridge-platform-wemo/issues/21#issuecomment-171392046)

**Comment by rudders** [comment] 2016-01-28 11:45
This should be resolved in the updated V0.6.5 version of homebridge-platform-wemo. Please update.

**Comment by kenderson** [comment] 2016-01-28 16:21
Thank you @rudders !!!

**Comment by rudders** [comment] 2016-01-28 22:41
@nfarina - I believe this can be closed mate. Further issues should be raised with the plugin(s) as necessary I believe.

**Comment by nfarina** [comment] 2016-01-28 22:42
:+1:

**Closed by nfarina** 2016-01-28 22:42 UTC
Labels: plugin issue
