### ISSUE TITLE
iControl/Xfinity Stopped Working

### ISSUE THREAD

**Issue by tropicalisurf** [nfarina/homebridge#1282] opened 2017-05-07 07:04 UTC
Hello,

I've been using the iControl module without any issues for more than a year now. Just recently, I started receiving this error and so I am now unable to use Homekit to control Xfinity. 

I'm not sure what changed but I feel that this started soon after an update to the Xfinity Home app. Maybe iControl also needs to be updated? I did uninstall everything and started from scratch but the issue remains...

Any help would be appreciated! Thank you!

```
5/6/2017, 11:54:21 PM] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:199
      var action = actionRegex.exec(body)[1]; // i.e. https://login.comcast.net/login
                                         ^

TypeError: Cannot read property '1' of null
    at iControl.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:199:42)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by fitzage** [comment] 2017-05-09 21:32
Duplicate of this one https://github.com/nfarina/homebridge-icontrol/issues/1

**Comment by AppleTechy** [comment] 2017-10-12 17:01
Please continue the discussion on the linked above issue under the plugin's github page

**Closed by AppleTechy** 2017-10-12 17:01 UTC
Labels: plugin issue
