### ISSUE TITLE
MiLight accessory does not pass IP address

### ISSUE THREAD

**Issue by chrisi21** [nfarina/homebridge#143] opened 2015-09-05 20:09 UTC
Thanks for your amazing work!

The IP address of the bridge does not flow through from the config.json file.  The zone is correctly passed, but the IP appears to be 255.255.255.255 (the constant DEFAULT_IP defined in node_milight_promise) this results in the lights associated with the zone on each of the MiLight gateways to turn on.  Example:  I have three MiLight gateways (192.168.69.51-53).  My config.json defines the accessory as follows:

{
"accessory":"MiLight",
"name": "Entryway",
"ip_address": "192.168.69.51",
"port": 8899,
"zone": 1,
"type": "rgbw",
"delay": 35,
"repear": 3
}

When this executes, all three gateways turn one RGBW zone 1.

I wish I could figure out the code myself, but it is beyond my ability.  Any help would be amazing.

**Comment by nzhome** [comment] 2015-09-06 14:09
could it be because you settings are invalid?  you wrote repear  instead of repeat ?

**Comment by dotsam** [comment] 2015-09-07 20:20
The MiLight shim is my code, and indeed, something isn't working right here. I'll take a look at it and get a PR to fix it in the next day hopefully.

**Comment by dotsam** [comment] 2015-09-07 23:53
This should be all fixed and working once PR #152 is merged in. Let me know how the MiLight shim is working for you, and if there's anything that you might like to see added or changed. Especially with non-RGBW bulbs, as I don't have any of those to see how it works real-world.

**Closed** 2015-09-08 00:30 UTC

**Comment by chrisi21** [comment] 2015-09-08 01:38
Hey @dotsam,

Thanks for fixing the code.  It is passing IP address now instead of the broadcast address.  Amazing stuff!  One more thing I've noticed is when I send a Hue command it sends the command but then seems to hang for a long period of time or requires me to restart Homebridge to get things back to normal.  Any idea what could be going on?

Thanks so much for your amazing contribution to this project!!!

-Chris

**Comment by dotsam** [comment] 2015-09-08 18:35
Good to hear @chrisi21 

I had been noticing this myself recently, but hadn't actually put my finger on the fact that it was caused by the hue command. The issue was a missing callback on the set hue function. I've just finished converting the accessory to a platform, and have fixed it there. I want to do a little more testing to confirm that this is all working correctly before getting it pushed into master here, but if you really wanted to try it out before then, you can grab the branch from my repo here: https://github.com/dotsam/homebridge/tree/milight-platform
