### ISSUE TITLE
Reading the current state

### ISSUE THREAD

**Issue by sweidinger** [nfarina/homebridge#6] opened 2015-03-06 10:56 UTC
What can we do to support reading the current state of a device, like a thermostat?
I'm working on a shim for the HomeMatic thermostat sensors. I can receive the variable with a http pull request.

**Comment by nfarina** [comment] 2015-03-06 17:16
Yeah I just didn't get around to adding support for this - I would be happy to review a pull request adding the functionality though!

**Comment by fritz-fritz** [comment] 2015-06-05 05:00
I think this is an important feature to work on adding... If I have time I intend to work on this. Obviously this will depend on the accessory or platform supporting the ability. I do not intend to implement any form of state caching.

**Comment by lepinsk** [comment] 2015-06-24 22:24
Hey @nfarina: I'd love to give this a go for Lockitron – I've written a ```getState()``` function that works but I'm not familiar with how to hook it up to a service characteristic. I see that ```TARGET_LOCK_MECHANISM_STATE_CTYPE``` has what I presume are read and write modes ("pr" and "pw") – any suggestions?

**Comment by maddox** [comment] 2015-06-24 22:31
I haven't looked at this *at all*, but is there any reason this can't be implemented in exactly the same way that accessories callout in `onUpdate()`?

**Comment by maddox** [comment] 2015-06-24 22:33
It looks like state updating was added a couple days ago - https://github.com/KhaosT/HAP-NodeJS/commit/40de0e9a32eeff2986495faf78a8018d339cd52b

**Comment by nfarina** [comment] 2015-06-24 22:34
Yes I think @snowdd1 is the person to ask about this…I'm not sure how to implement support for it though.

**Comment by maddox** [comment] 2015-06-24 22:43
It looks like we can just use it exactly like I had described before I knew anything. Heh. 

I'm gonna give it a go tonight to see if I can get state querying support on the Wink platform.

**Comment by lepinsk** [comment] 2015-06-24 22:59
I'll keep an eye on what you manage and try to do the same for the
Lockitron.

**Comment by maddox** [comment] 2015-06-25 02:31
Ok, so...I actually got this working. The problem is, the `onRead` isn't async. If I return something immediately, it works. But if I have to go async to fetch the value (which basically every js lib does), it fails...because, it's not async.

So, if you can return immediately, or block while doing it, this works :/

The other thing is, trying to re-engineer the `onRead` to accept a callback.

I'll keep looking at things.

**Comment by maddox** [comment] 2015-06-25 02:38
Ok, ✨, I got `onRead` working async!

I'm going to open a pull at [KhaosT/HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) to add it. Once it lands I'll open a pull for Homebridge.

**Comment by nfarina** [comment] 2015-06-25 03:00
That is awesome!

**Comment by maddox** [comment] 2015-06-25 03:01
Ok, it wasn't actually being returned right. lol. So siri never got the returned value. I'm in callback hell right now trying to bubble the callbacks all the way back up.

Stay tuned...

**Comment by maddox** [comment] 2015-06-25 05:33
OK, 💥, I got it working. I opened a pull at KhaosT/HAP-NodeJS#82. 

When/If it lands, we can pull it in and start returning current state values. If it does, I'll open a pull with the Wink platform updated to read states to kick things off.

**Comment by maddox** [comment] 2015-06-25 05:41
Merged!

Pull coming up.

**Comment by nfarina** [comment] 2015-06-25 05:50
:fireworks:

**Comment by snowdd1** [comment] 2015-06-25 16:17
As I started the onRead property some time ago as a functionality demo, I want to understand what the issue with synchronous query of the status was. @maddox  , can you please explain the issue to me?
Because I think I ran into something similar when I programmed the KNX accessory factory.
I always assumed that Siri didn't wait for my answer (If the status query took a second or so she (it?) told me my lights hadn't answered this time - and in the log I saw HAP's answer shortly after that...

**Comment by nfarina** [comment] 2015-06-25 16:27
Hm .. it seems like Siri would have to poll the HAP server to fetch state, and that operation can naturally take some time - I think the question is, what is Siri's timeout exactly? Is it a few seconds or a few milliseconds?

**Comment by snowdd1** [comment] 2015-06-25 19:38
When looking at @maddox ' solution, I think it's probably in sub-second area, until Siri needs to get the HEAD of the answer. By doing it asynchronously the header is sent, and the remainder of the body is send when the device answered. In my first try I held the complete answer including header until I had the value; running in the time out.

**Comment by nfarina** [comment] 2015-06-25 20:18
So your home automation bus system [described in #82](https://github.com/KhaosT/HAP-NodeJS/pull/82) sounds ideal - the system is very proactive in giving you state updates.

For the accessories supported by HomeBridge so far, the state of things is:

 - LiftMaster: Today, polling only (cloud), maybe possible to get "comet" style long-poll updates
 - Lockitron: Polling only (cloud)
 - Sonos: Polling only (fast, local)
 - WeMo: Polling only (local, speed unknown)
 - Xfinity Home: Polling only (cloud)
 - Carwings: Polling only (cloud / 3G, extremely slow, 10-30 seconds)
 - HomeMatic: Unknown

So if we had to return state immediately then it would be probably impractical to support most of these devices. The description of the HEAD behavior sounds intriguing though - it would be great to figure out how much time we get after delivering the header to finish the response.

**Comment by snowdd1** [comment] 2015-06-25 20:30
:-) you reckon how long I have been waiting for Siri to support home automation?

**Comment by nfarina** [comment] 2015-06-25 20:34
Hah, quite some time I'd imagine - Your home sounds pretty amazing!

**Comment by snowdd1** [comment] 2015-06-25 20:52
I'd even played with https://github.com/plamoni/SiriProxy some time, until Apple broke it with iOS7. I really keep my thumbs pressed they don't wreck our work by locking out all non-certified implementations!
And yes, I really have a "smart home" by all means. The [WAF](https://en.wikipedia.org/wiki/Wife_acceptance_factor) was very low at the beginning, but she really got used to it, and doesn't want to miss it any more.

**Comment by lepinsk** [comment] 2015-06-25 22:05
> Lockitron: Polling only (cloud)

Lockitron also supports webhooks, so it would be possible to register for these and digest them as they come in (with appropriate bridging or open router ports), would it not? I wonder how many other services also have webhook support. If homebridge stored and cached these values, it would make Siri lookup near-instantaneous...

(For the record, I'm seeing most GET calls to Lockitron's API returning in ~400-500ms.)

**Comment by maddox** [comment] 2015-06-25 22:09
Wink has subscriptions as well, I'm sure they're webhooks. But HomeBridge/HAP-NodeJS isn't really set up to take requests like that either. Not to mention having to forward ports to route the requests. :/

**Comment by lepinsk** [comment] 2015-06-25 22:20
In my case I'll probably use a tool like [ultrahook](http://www.ultrahook.com/) to bounce webhooks to the local machine.

**Comment by nfarina** [comment] 2015-06-25 23:32
Wow, UltraHook looks awesome. Bookmarked!

**Comment by maddox** [comment] 2015-06-26 03:02
So, I'm not gonna lie. I'm not sure where to go from here. This topic is spread across 3 different threads now, heh.

I certainly don't want to introduce anything that de-stabalizes what we have. But I'm also staring at sorrrrrrt of working stuff. I'd love some suggestions on what we could do to make what [I've done](https://github.com/KhaosT/HAP-NodeJS/pull/82) work.

/cc @nfarina @snowdd1

**Comment by nfarina** [comment] 2015-06-26 04:19
OK so I just did some testing at home and Siri's timeout (at least on iOS 8.3) seems to be exactly 10 seconds. This is using @maddox's `async-onread` branch that calls `writeHead` immediately then waits for the callback to be fired after determining actual accessory state to write the response body.

So I do think it seems reasonable to support accessories that must fetch their status from a local device or from the cloud - and Siri seems designed for this, she'll even print "Checking around the house..." while she's waiting for a response.

However I do agree with @snowdd1 that patching the async callback mechanism into HAP-NodeJS as-is is a bit messy. And the more immediate problem was that it broke bridged accessories? So I think if these two issues can be solved then a strong case can be made to support async onRead.

**Comment by maddox** [comment] 2015-06-26 05:04
> seems to be exactly 10 seconds

That's legit. Seems to me we can totally be async. If you can't give an answer in 10s, thats your (the shim's) problem right?

> So I do think it seems ***un***reasonable to support accessories that must fetch their status from a local device or from the cloud - and Siri seems designed for this, she'll even print "Checking around the house..." while she's waiting for a response.

Yeah totally. Also, HomeKit itself supports bridge hubs. These hubs may at some time have to query a device after it hasn't heard from it for a while. So it sounds like HomeKit is prepared.

> However I do agree with @snowdd1 that patching the async callback mechanism into HAP-NodeJS as-is is a bit messy.

Is it that bad that the characteristic updater uses a callback? I mean, I'm not sure how else I could have done it. I had to got allllllll the way up the call stack or else callbacks can't really work.

I'd love some suggestions in how to make the `onUpdate` support a callback, but not have to patch all the way up the call stack. But like, you have to right?

> And the more immediate problem was that it broke bridged accessories? 

If this means that I just didn't patch `BridgedAccessory.js`, I can totally do that, that's pretty simple.

**Comment by maddox** [comment] 2015-06-26 05:08
Ok, I just patched `BridgedAccessoryController.js` here - https://github.com/maddox/HAP-NodeJS/commit/6b895d07c2e8262dae9ec38abcf99e3e654584f4

**Comment by nfarina** [comment] 2015-06-26 05:42
I'm actually having a bit of trouble figuring out how `onRead` is supposed to work, either in sync land or async land. `Characteristic.js` looks for `onRead` in the `options` dict, but `options` is explicitly constructed in `BridgedCore.js` (and `Core.js`) and `onRead` is never assigned.

**Comment by snowdd1** [comment] 2015-06-26 08:38
This is really going to be an 24/7 operation... We still need participants in Asia...


@maddox : Is your implementation really async? I did not find the code where you inserted the event handler and return control to the calling function. All I see is a call stack up and down, but never going async. Is this part not in the github repositories? Where would the actual reading from the device happen?

@nfarina : The sync version is supposed to be straightforward (if one can say so with javascript):
The onRead property is defined as a function in the accessory, as part of [services[1].characteristics[1]](https://github.com/snowdd1/HAP-NodeJS-KNX/blob/experimental/accessories/GarageDoorOpener_accessory.js) . When the accessory.js file is read, its properties are copied into an characteristics.js type of object. In Core.js (or BridgedCore.js) the function reference was supposed to be copied into options.onRead but this part got lost in my process of pushing to github... probably that's why it never worked in the first attempt of @maddox .
There should be line after line 73: 
```javascript
    onRead: accessoriesJSON[i].services[j].characteristics[k].onRead,
```
Your right, I wrecked the repo. d*mn.

**Comment by nfarina** [comment] 2015-06-26 12:31
OK no worries, just glad I'm not crazy! We can fix it.

Next question is to the purpose of `locals` and `onRegister`. Is the purpose of these properties to provide class-like behavior to `HAP-NodeJS`'s native "dictionary-based accessories"? It seems like you are using `onRegister` like an init function, and `locals` as a way to make custom properties "survive" the normal process of accessory creation.

**Comment by snowdd1** [comment] 2015-06-26 15:07
I introduced **locals** to pass variables (encapsulated in an object - most flexible) to the characteristics through the copying/referencing process in *core* and *bridgedcore*. As I am instantiating 10s of similar accessories, I need some more data in the characteristic object to be passed to the bus gateway server to address the right device (such as a bus address) - in a accessory factory there is little room for hardcoding some literal constants (I did some, and it is still aching.)

In fact, the **onRegister** together with the locals work a bit like a reverse callback you guys are implementing: When instantiating the characteristic object through its constructor, it passes **itself** to the onRegister function, which passes it to the event hook. The purpose is simple to have access to the characteristic object when a status change event occurs - then it calls characteristic.updateValue(value, null); with the updates value (eg. external event: Wife pressed light switch). The characteristic object then caches the value internally and takes care of propagating the value update to all peers if they are event enabled.

**Comment by snowdd1** [comment] 2015-06-26 15:17
Do you have an accessory with an asynchronous data fetch in the repo?

**Comment by nfarina** [comment] 2015-06-26 15:27
The "Garage Door" sample accessory in `HAP-NodeJS` should work in [#86](https://github.com/KhaosT/HAP-NodeJS/pull/86) - just replace `callback(undefined)` with `callback(1)` for instance.

**Comment by snowdd1** [comment] 2015-06-26 15:55
Sorry, I was imprecise: A concrete handler which really acts asynchronously.

**Comment by maddox** [comment] 2015-06-26 15:56
@snowdd1 you can see an example here - https://github.com/nfarina/homebridge/pull/35/files#diff-eb07a999d3ffe63589fef818b31e85e9R211

**Comment by nfarina** [comment] 2015-08-21 20:31
Reading the state is now possible with `onRead` (and will be possible with `characteristic.on('get',...)` with new API, so I'm closing this.

**Closed by nfarina** 2015-08-21 20:31 UTC
