### ISSUE TITLE
Datatype Mismatch

### ISSUE THREAD

**Issue by pdlove** [nfarina/homebridge#575] opened 2016-03-20 17:50 UTC
I've been working on resolving an issue with my plugin that was causing large numbers of devices to vanish from HomeKit or be unresponsive.
What I discovered is that the JSON coming from smartthings has the number in quotes which is making it a string. When I turn this around and send it to the Brightness Characteristic without explicitly converting to a number, it sends as a string which crashes HomeKit.

Is this expected behavior, or does Apple have a flaw in their logic?

**Comment by KraigM** [comment] 2016-03-20 17:53
I have been dealing with this too.  I think they aren't accepting bools for the BOOL type (only numbers).  But thats just a possibility (someone is trying to verify that).

**Comment by KraigM** [comment] 2016-03-20 17:54
The only user who has reported the issue is on a beta version of iOS 9.3 so maybe its a bug in that or a new policy change?

**Comment by KraigM** [comment] 2016-03-20 17:57
If either are the case, the best solution might be to augment the HAPServer code to auto clean the data (if BOOL use 0 or 1, if INT convert to integer, etc)

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L240

**Comment by pdlove** [comment] 2016-03-20 17:57
With the number vs strings, I've had many people not on 9.3 with the issue.
On the Bool... I'm on 9.3 and see the accessories file is passing bools as true/false without quotes without issue. I bet that is the difference.

**Comment by KraigM** [comment] 2016-03-20 17:59
Well true/false without quotes are json bools, however all the constants in HAPServer seem to use 0 and 1 instead.  But the default for a bool in HAPServer is still false (not 0).

**Comment by KraigM** [comment] 2016-03-20 18:01
Though I could see Apple not auto converting string numbers to numbers since json actually has a number type

**Comment by KraigM** [comment] 2016-03-20 18:01
But yes, it could be a nice thing to throw into HAPServer

**Comment by KhaosT** [comment] 2016-03-20 20:32
I mean bool should be fine with both 0/1 or true/false since internally it's all NSNumber. However, for numerical values, HomeKit is expecting a numerical value in JSON instead of string... Ideally plugins should ensure that they passed in value that matches the type but if you guys really want, I can add type conversion in hap-nodejs 😊

**Comment by KraigM** [comment] 2016-03-20 20:39
@KhaosT well "supposedly" me sending 0/1 instead of true/false fixed the issue for the user.  It doesn't happen to anyone else from what I can tell, but most users are likely not on iOS 9.3 beta.  Maybe the beta has a bug that makes it no longer convert JSON bools to NSNumbers.  Anywho, he said it "randomly happens" so he will let me know tomorrow.

But yes @KhaosT, throwing type checking/conversion into HAP-NodeJS might be good regardless.  I know the string v. int issue has come up for me to (my own stupidity lol).

**Comment by pdlove** [comment] 2016-03-20 21:40
For me, it has come up only because I trusted the Smartthings API to give me proper JSON and simply passed the value on. Finding the issue was like knocking down a brick wall by hitting it with my head.
I think it would be handy to have a guide for API developers "You Screwed It All Up" and have this on the list.

**Comment by KhaosT** [comment] 2016-03-21 04:54
Alright, hap-nodejs v0.2.8 addressed this. For homebridge, please update to v0.3.2 to get this feature.

**Comment by leoneleone** [comment] 2016-03-22 15:07
Thanks for the recent update. This has fixed command execution failures I was having with more than one plugin. My Homebridge/HomeKit setup works much faster now when using Siri Commands

**Comment by pdlove** [comment] 2016-03-22 15:30
Thanks guys for the help on this. I'm glad to hear I'm not the only plugin developer who had a plugin plagued by it!

**Comment by KhaosT** [comment] 2016-03-23 05:59
I'll close the issue for now. If you find a case I missed, feel free to open a new issue :)

**Closed by KhaosT** 2016-03-23 05:59 UTC
