### ISSUE TITLE
Z-wave Switches/Outlets

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#423] opened 2015-12-15 03:42 UTC
Has anyone gotten z-wave switches or outlets to work through a wink hub? They obviously show up in wink app, but not in Homebridge. Just curious.

**Comment by AppleTechy** [comment] 2016-01-06 22:37
There should be an update pushed out by the end of the week by @pdlove or @KraigM which will bring support for both

**Comment by Jborn4christ** [comment] 2016-01-06 22:59
Awesome news

"Live your life as if it were a work of art."
-Abraham Joshua Heschel

**Comment by AppleTechy** [comment] 2016-01-06 23:07
kraigm/homebridge-wink#5

**Comment by AppleTechy** [comment] 2016-01-06 23:50
close #423

**Comment by AppleTechy** [comment] 2016-01-06 23:51
close

**Comment by AppleTechy** [comment] 2016-01-06 23:53
duplicate of Kraigm/homebridge-wink#5

**Comment by AppleTechy** [comment] 2016-01-06 23:53
duplicate

**Closed** 2016-01-06 23:58 UTC
