### ISSUE TITLE
Having duplicate accessory names causes error 

### ISSUE THREAD

**Issue by wind-rider** [nfarina/homebridge#640] opened 2016-05-21 14:08 UTC
**What I did:**
- Installed homebridge & hue plugin
- Set up bridge ip in config.json, registered username in config.json
- Paired with phone
- Changed lamp names I named two lamps the same ("Ceiling") since they are in different rooms -> I wanted to say something like "hey Siri, turn on the ceiling lamp in the bedroom" instead of naming the lamps "ceiling bedroom" and "ceiling hall".

**Result:** homebridge+hue plugin crashes after a restart

**Workaround:** renaming one of the "ceiling" lamps to "ceiling bedroom" so that the names are not duplicate anymore helped

**Cause:** UUID is generated based upon the accessory name in https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/uuid.js like in https://github.com/nfarina/homebridge/blob/620c8473b86fe21fe473b18894e6ca592caeb13b/example-plugins/homebridge-samplePlatform/index.js#L183

**Possible solutions:** 
- the "name" should be a concatenation of accessory name and room name to make them unique per room (fix in nfarina/homebridge)
- this UUID shouldn't be linked to the name but to the lamp ID (lamp zigbee address) so that the UUID is unique (fix in homebridge-philipshue)
- the UUID should be not based on a hash which makes it predictable (fix in HAP-NodeJS)

**Log:**

```
[2016-05-14 20:18:01] Loaded plugin: homebridge-philipshue
[2016-05-14 20:18:01] Registering platform 'homebridge-philipshue.PhilipsHue'
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loaded config.json with 0 accessories and 1 platforms.
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loading 1 platforms...
[2016-05-14 20:18:01] [Philips Hue] Initializing PhilipsHue platform...
[2016-05-14 20:18:01] [Philips Hue] PhilipsHue Platform Plugin Version 0.0.2
[2016-05-14 20:18:01] [Philips Hue] Fetching Philips Hue lights...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 88c675f0-a405-4b4e-b2e6-1ad5e94d45c1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-philipshue/index.js:140:9
    at resolveValue (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/hue-api/utils.js:34:13)
    at _fulfilled (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/l
```

**Comment by ptz0n** [comment] 2017-01-25 19:29
This issue is still valid, but should really be fixed in [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS).

**Comment by snowdd1** [comment] 2017-01-25 20:26
Sometimes the only thing you get from platforms is the name. The only way to re-connect the devices to their cached shadows is to use some UUID. Platforms **can** provide their own UUIDs, but if they don't (as the plugin @wind-rider mentioned seems not to) , the name is used for UUID creation. That makes it *predictable*, but more important, that makes it *reproducible*, which it must be.  

You cannot use the room as additional key, because the rooms are not known to homebridge (that is in iCloud/HoemKit only), unless you put the room name into the accessory name, which seems a common pattern.  

So the only possible of the proposed solutions is: fix the plugin to provide unique UUIDs for the accessories.

**Comment by KhaosT** [comment] 2017-01-25 20:30
Yeah, I believe @snowdd1 covered the problem really well. I don't think there is anything actionable since we expect plugin to provide a *universally unique* identifier for each accessory and in this case clearly the plugin failed.

**Comment by ptz0n** [comment] 2017-01-26 07:00
I'm thinking that a model + serial number is a much better candidate for generating unique UUID's.

**Comment by KhaosT** [comment] 2017-01-26 07:07
but those information are populated by plugins. It's not guaranteed that all plugin will populate serial number uniquely.

**Comment by snowdd1** [comment] 2017-01-26 07:19
... and if they do, they already can provide it as UUID base ...

**Comment by snowdd1** [comment] 2017-01-26 07:46
And we had this discussion as far back as 2015 already. See here https://github.com/nfarina/homebridge/issues/203 (that's 400+ issues time travel)  
The code looks somewhat ~~different~~ better today, but the issue at hand stayed the same: If platforms don't provide a unique identifier, things can go south.

**Comment by ptz0n** [comment] 2017-01-26 07:58
Using `displayName` is a fair fallback. But if the plugin provide a UUID's, use those.

**Comment by wind-rider** [comment] 2017-10-31 19:15
Has anybody looked into this issue further? If unfixed, this issue can cause a lot of confusion to users...

**Comment by ptz0n** [comment] 2017-10-31 19:17
@wind-rider Have you tried the latest version?

**Comment by KhaosT** [comment] 2017-10-31 19:17
This is really a issue plugin developer needs to solve. Homebridge expects plugin to provide unique identifier to each accessory and right now some plugins used name as unique identifier which breaks when user have multiple accessories with the same name under a plugin.

**Closed** 2017-10-31 19:17 UTC

**Comment by tealord** [comment] 2017-12-01 13:52
Just if someone is running into this issue - I am using the plugin `homebridge-script` and the following configuration fixed the error:
`{
  "accessory": "Script",
  "uuid_base": "053a1d3c-d677-11e7-b423-0019993a65df",
  "name": "Lights",
  "on": "~/scripts/lights/on.pl",
  "off": "~/scripts/lights/off.pl",
  "on_value" : "true",
  "exact_match": true
},`
