### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by fboulegue** [nfarina/homebridge#946] opened 2016-11-23 20:41 UTC
Since yesterday my home bridge crashes after a time.... anyone can help me why?

<img width="539" alt="bildschirmfoto 2016-11-23 um 21 40 42" src="https://cloud.githubusercontent.com/assets/2719590/20578059/a7067186-b1c5-11e6-91fa-8be9240a617b.png">

**Comment by RXM307** [comment] 2016-11-23 21:39
Looks like a duplicate of #31

**Comment by KhaosT** [comment] 2016-11-23 22:18
Nope, this one is triggered by ``homebridge-harmonyhub``. Looks like it has a limitation of 6 clients. Please file a issue with plugin developer.

**Closed by KhaosT** 2016-11-23 22:18 UTC
