### ISSUE TITLE
Error Logitech Harmony

### ISSUE THREAD

**Issue by Frakke0** [nfarina/homebridge#185] opened 2015-09-17 16:55 UTC
<img width="1075" alt="screen shot 2015-09-17 at 18 53 38" src="https://cloud.githubusercontent.com/assets/14334330/9940033/9122d948-5d6d-11e5-811f-22af1825c393.png">
<img width="1068" alt="screen shot 2015-09-17 at 18 53 48" src="https://cloud.githubusercontent.com/assets/14334330/9940034/91256e06-5d6d-11e5-8306-d990e90aebfa.png">

This error i'm getting when running npm run start.
Anyone who can help me?
You would be a hero!

Regards

**Comment by lyonsad** [comment] 2015-09-17 17:04
im getting this now as well

**Comment by maddox** [comment] 2015-09-17 17:29
The API could have changed. Or they're not sending ANYTHING back anymore. I sure hope that's not it. Someone mentioned to me once that they heard a rumor that harmony was removing local control, going cloud only. Which, would be insanity if you ask me.

Did the hubs recently get an update?

**Comment by Frakke0** [comment] 2015-09-17 17:34
Hmm, a few weeks ago, I installed an update. But not recently..
I really hope it isn't cloud only :)

**Comment by maddox** [comment] 2015-09-17 17:38
> I really hope it isn't cloud only :)

Tell me about it. I JUST bought into Harmony after hating on them for 10 years, only because of the network addressable hub :grimacing:

**Comment by Hans-S** [comment] 2015-09-18 07:27
I'm running this on a Mac, and eventually managed to fix it. Not a nice and clean solution, but it did get rid of this error for me. 

The problem is that the selected/default parser doesn't handle CDATA, while the identity item (and others) are contained in a CDATA enclosure in the reponse. Since the parser doesn't handle CDATA, the identity is left out by the parser, and you get the mentioned error.

I created an issue on the harmonyhubjs-client community for this, and was pointed to te expat parser, which does handle CDATA. I hardcoded the use of the expat parser, in the following files:
 
homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js
homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/Parser.js
 
change ltx to node-expat as shown here:
var LtxParser = require('./parsers/node-expat')
  , LtxParser = require('ltx/lib/parsers/node-expat')

It does require the expat parser to be available and buildable. So when homebridge is installed, check if node-expat was built correctly:

homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/parsers/node-expat.js
homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat

You might get a security error, possibly when running on a remote Mac via remote desktop maybe, when building node-expat. Try building it locally, or try "sudo nam install --unsafe-perms". Probably best to do that for the node-expat module only.

**Comment by maddox** [comment] 2015-09-20 02:45
This is crazy, I was just running this totally fine earlier tonight in another project of mine: https://github.com/maddox/harmony-api, but after an update, boom, it started getting this error as well.

Did a module get updated (i wiped my `node_modules` and reinstalled them all) to effect this change?

**Comment by maddox** [comment] 2015-09-20 02:50
OK, I see, it has to do with how my packages got built after my system was upgraded in some fashion. This is unfortunate :(

**Comment by KraigM** [comment] 2015-10-22 04:32
This should be fixed as well as other fixes and enhancements have been merged in as part of #299.  See if that works for you guys

**Closed** 2015-12-10 05:52 UTC
