### ISSUE TITLE
Cannot add a bridged Accessory with same UUID as another bidged Accessory using config-sample.json

### ISSUE THREAD

**Issue by andig** [nfarina/homebridge#228] opened 2015-10-05 08:03 UTC
Getting this error on first startup (`npm run`) after:

  - cloning repo
  - copying config-sample.json to config.json
  - cleaning config.json of any accessories with non-json comments

Error happens when initalizing `[Kitchen Lamp]` HTTP Accesory?

**Comment by snowdd1** [comment] 2015-10-05 08:22
If you have a platform enabled that returns another "Kitchen Lamp" as name this might happen, though it is not supposed to happen. 
The UUID is generated using the accessory/platform object name (constructor name) and the given name (returned by platform or with accessories, as written in config.json).
There was another issue here (https://github.com/nfarina/homebridge/issues/203) in which a similar behavior was described, but was unable to reproduce by other user afaik.

**Comment by andig** [comment] 2015-10-05 09:42
> If you have a platform enabled that returns another "Kitchen Lamp" as name this might happen, though it is not supposed to happen. 

That's what I've thought but I only have the items from the `config.json`. I've quickly dug through the accessories and couldn't find any duplicates. I'm suspecting that the nodehap library might be responsible for the duplicate?

**Comment by andig** [comment] 2015-10-05 10:57
Found it. https://github.com/nfarina/homebridge/blob/master/config-sample.json#L91 has a `Kitchen Lamp` zone which is the same as the Http accessory at https://github.com/nfarina/homebridge/blob/master/config-sample.json#L162.

As https://github.com/nfarina/homebridge/issues/203 describes the uuid prefixing is broken: `Object.Kitchen Lamp` is most likely not what was intended, is should rather by the accessory type plus the actual name, preferable plus the serial number of the device if any.

**Comment by nzhome** [comment] 2015-10-05 11:33
you have both types of lamps running in your house?  http ones? and LimitlessLED/milight ones?  that is not common at all.  also I would recommend you to change the names of your lamps to be correct for your home,    config-sample should just be that only.. a sample. You have to actually name your devices in the home better than that.

**Comment by nzhome** [comment] 2015-10-05 11:34
I would not touch the uuid prefixing, because it might break the Siri aspect of names.  I would prefer it error'd out like it has on you.  keep the names in your house unique across all devices.

**Comment by SphtKr** [comment] 2015-10-11 03:48
Did this get fixed by #233? Looks like the same or a related issue that was being fixed.

**Closed** 2016-01-07 00:56 UTC

**Comment by anthonywebb** [comment] 2016-11-08 09:15
I am hitting this as well.  IMHO naming each device uniquely is a bad move.  Each might be named uniquely within a room, but unique globally?  I have 100 devices and a lot of overlap on names, after all, a fan is a fan, it might be in the family room or in the master, but why cant I simply call it "fan"?

**Comment by snowdd1** [comment] 2016-11-09 11:38
I think Apple noticed that as well and changed the uniqueness requirements for devices and services with iOS 10 or 10.1

**Comment by snowdd1** [comment] 2016-11-09 11:44
However, depending on the plug is you use, the UUIDs might be based on the names, and those are required to be unique! So this is a plug-in issue as well.

**Comment by phaus** [comment] 2017-01-30 09:19
+1 for that issue… 
So can I ignore it? Will it be fixed?

**Comment by bencollier** [comment] 2017-02-17 20:47
For anyone else - found this problem when I hid an accessory in the Eve app from Elgato.

**Comment by RobotLimeLtd** [comment] 2017-10-02 13:50
This issue happens if you have more than one Harmony remote in your house.  In that scenario, it's quite usual to have two Activities called "Watch TV", but of course they refer to different rooms of your house.
